### ISSUE TITLE
explanation of "join" function

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#109]
This does not work in dev branch.  if you try to join a segment you either get:
 Segments with the same name cannot be joined  
or

you get:
 Joined segment must start with higher residd 

(which has an extra d ...)

What is the expected usage of this function?

**Comment by dww100** [comment]
The idea was to deal with two situations; firstly, reconnecting incorrectly split chains and secondly correcting issues where the chain ID was scrambled in the input. This was very much a first draft but I believe it is working as intended. This wasn't intended to be for joining structures if the residue numbering hadn't already been handled.

**Comment by madscatt** [comment]
Okay, I will add the following to the pdbrx docs 

join: to join two segments at the specified row into the name of the segment of the row chosen. Note that you can not join two segments of different molecular types (moltypes), nor can you join two segments if they contain the same resid (residue numbering).

until we decide to expand the options that would enable joining segments in more advanced use cases.
