### ISSUE TITLE
multi-component analysis: read file written by sascalc

### ISSUE THREAD

**Issue by skrueger111** [madscatt/zazzie#149]
Multi-component analysis will have the option to either input Rg as a function of fraction D2O manually or read it from a sascalc output file.  Currently, sascalc writes the contrast-dependent Rg in a log file that is generated along with each model SANS curve, meaning that there is a separate log file for each fraction D2O.  Sascalc will need to write a SINGLE file containing Rg vs fraction D2O. Here, Rg can be from a single structure or an average Rg from an ensemble (or sub ensemble) of structures.  The key is that it changes as a function of fraction D2O for model contrast variation data.

**Comment by skrueger111** [comment]
This (future) [sample_sascalc_output_file.txt](https://github.com/madscatt/zazzie/files/14936386/sample_sascalc_output_file.txt) is intended to be read by the stuhrmann parallel axis module.

**Comment by madscatt** [comment]
This is the data from the file:

#Information such as date, module used, sassie version, etc.

#Molecule information such as PDB input files, H-D exchange, deuteration, etc.

```
#NEUTRON contrast-dependent Rg (A):
# frac D2O, Rg
 0.00	 38.8
 0.20	 35.1
 0.85	 40.7
 1.00	 60.0
```

**Comment by skrueger111** [comment]
Closing this issue as "not going to implement".
