### ISSUE TITLE
Evaluate data path for decomposition

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#156]
Make sure that file-path variables introduced in decomposition module is going to work with GenApp paths.

`        self.data_file_name = self.path+"0.dat, "+self.path+"10.dat, "+self.path+"20.dat, " + \
            self.path+"40.dat, "+self.path+"80.dat, " + \
            self.path+"90.dat, "+self.path+"100.dat"
`

**Comment by madscatt** [comment]
Gui mimic wants the files in the directory of the executable, which would have to be the bin directory in GenApp.  This needs to be in the path of the run_name etc. and/or if uploaded by the user via the GUI.

**Comment by skrueger111** [comment]
This issue has been addressed since Decomposition now successfully reads SANS contrast variation data files that are either uploaded from the user's local computer or from their work space on the server.
