### ISSUE TITLE
Rename variable(s)

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#170]
sn_amplitude should be changed to signal_to_noise_amplitude, which is used in multicomponent analysis module(s).

**Comment by skrueger111** [comment]
While not user inputs, the following variables should also be changed for consistency:

sn_mean to signal_to_noise_mean
sn_stddev to signal_to_noise_standard_deviation
sn_bgd to signal_to_noise_background

**Comment by madscatt** [comment]
Test comment

**Comment by madscatt** [comment]
another test comment

**Comment by madscatt** [comment]
Made changes and ran gui_mimic to test.
