### ISSUE TITLE
Test whether newly-added __init__.py in src/sassie prevents the docs from compiling correctly

### ISSUE THREAD

**Issue by skrueger111** [madscatt/zazzie#176]
In a recent commit, an \_\_init\_\_.py file was added to the src/sassie folder.  As I remember, this file will be an issue when compiling the docs.  I would like to delete the file, but Joseph thinks it may be required by the installer. I have been installing modules in the Linux VM on my laptop without this file, so I don't think it is needed.

TODO:  Test whether this file prevents the docs from compiling correctly.  If so, remove it and confirm that the installer doesn't need it.

**Comment by madscatt** [comment]
Yes, the __init__.py file must be there for sassie to function as an importable package.

**Comment by skrueger111** [comment]
Since the file is needed, 

new TODO:  Test whether this file prevents the docs from compiling correctly.  If so, open a new ticket to research an alternative for compiling the docs.

**Comment by skrueger111** [comment]
The docs still compile using the same instructions that are in the zazzie Wiki.  The only difference is that all of the modules are now under the "sassie package", requiring the user to drill down one more level to see the documentation for the modules.  The Module Index still allows the user to find documentation for a particular module quickly.  Closing this ticket.
