### ISSUE TITLE
Match Point Analysis:  Add match point to JSON file for plotting

### ISSUE THREAD

**Issue by skrueger111** [madscatt/zazzie#180]
Add the (single) data point for the calculated match point to the JSON output file so that the calculated match point can be added to the output plot.  The data point is the fraction D2O that corresponding to the match point, i.e., (x = match_point +/- match_point_error, y=0).

**Comment by madscatt** [comment]
@skrueger111: please identify the data variable names for the match point so the actual numbers can be propagated. We should also consider cases where a valid match point estimate is not obtained. In other words, what should we plot if the contrast values do not intersect the y-axis.

**Comment by skrueger111** [comment]
@madscatt:  The x variable is match_point +/- match_point_error, where match_point and match_point_error ARE the variable names.  Yes, we should check to make sure a valid match point was found.  If not, I’m not sure we should make any plot at all.  We should also check whether the match point is > 1, as is the case for perdeuterated molecules and, to be thorough, < 0, as would be the case for CH2 or CH3.  (This would be unexpected since we are talking about the match point of the complex.) In that case, I don’t think we would want to put the match point on the plot. Some test plots should be made before deciding.  Related to issue #181.

**Comment by skrueger111** [comment]
Added the match point to the json file.  Tested multi-component analysis to make sure the match point was added.  Test json output file attached.  Committed the change.  Also tested the plot using the GenApp Advanced Tutorial plotly test utility.  
[matchpoint_testdata1.out.json](https://github.com/madscatt/zazzie/files/15475000/matchpoint_testdata1.out.json)
