### ISSUE TITLE
contrast calculator plotting

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#193]
The 2.7 code uses Gnuplot methods.  These plots need be managed by plotly using the same methods used in other modules.

**Comment by skrueger111** [comment]
The Gnuplot methods were not ported to Python 3.  Plotting will be handled by GenApp via a JSON file (see issue #197 ).
@madscatt :  I think we can close this issue.

**Comment by skrueger111** [comment]
I'm closing this issue since the only thing left is to add the method to make the JSON file for the plots, which is covered by ticket #197
