### ISSUE TITLE
Convert Contrast Calculator to Python 3

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#194]
Carry out the conversion.  Do not port Gnuplot functions.  See #193 for tracking the upgrade from Gnuplot to Plotly.  Check by running system integration tests.

**Comment by skrueger111** [comment]
The directory contains different gui mimic and contrast calculator files.  The files containing "1.0" are the 1.0 versions. The gui mimic file without the "1.0" is the right one to use. The contrast_calculator.py and contrast_calculator_new.py files are the same except for some different formatting in the comments and one "else" statement at the end that is executed if results aren't being plotted.  The contrast_calculator_new.py file had carriage returns in it.  I removed them and pushed a new version.  Either version can be used for the conversion to Python 3.

**Comment by madscatt** [comment]
Updated module and associated files to Python 3.  The program runs using gui_mimic.   @skrueger111 : please carry out system integration tests.

**Comment by skrueger111** [comment]
@madscatt : I tested contrast calculator from the gui mimic.  I tried cases where both fasta and pdb files are read.  I had to make changes in the call to sasmol in order to read the pdb files.  Changes are pushed to Github.  Should we close this ticket?

**Comment by madscatt** [comment]
Great news.
