### ISSUE TITLE
The Isopeptide module of TAMC does not use the same input parsing as the other modules

### ISSUE THREAD

**Issue by stvn66** [madscatt/zazzie#30]
I changed the gui mimic input from `resid<48` to `resid < 48` and it crashes with the error:
```
raceback (most recent call last):
  File "gui_mimic_iso_peptide.py", line 106, in <module>
    simulation.main(variables, txtQueue)
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo.py", line 124, in main
    self.initialization()
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo.py", line 543, in initialization
    self.setup_groups()
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo.py", line 359, in setup_groups
    torsion.setup(self, group_number)
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo_utilities/torsion.py", line 70, in setup
    setup_torsion_parameters(other_self, mol, group_number, pvars)
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo_utilities/tamc_utilities/setup_torsion_parameters.py", line 335, in setup_torsion_parameters
    main_pivots_indices, pvars.main_pivots_masks[group_number], pvars.residue_main_pivots[group_number] = torsion_parameter_module.assign_main_pivots(group_flexible_molecule, pvars)
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo_utilities/isopeptide_bond_torsion/isopeptide_bond_torsion_parameters.py", line 185, in assign_main_pivots
    residue_basis_strings = build_basis_strings(residue_main_pivots,residue_main_pivots_outside,residue_main_pivots_list, pvars.flexible_basis)
  File "/opt/intel/intelpython35/envs/sassie/lib/python2.7/site-packages/sassie/simulate/monte_carlo/monte_carlo_utilities/isopeptide_bond_torsion/isopeptide_bond_torsion_parameters.py", line 94, in build_basis_strings
    cter_resid = int(cter_list[cter_list.index('resid')+1])
ValueError: invalid literal for int() with base 10: '76)'
```

**Comment by hailiangzhang** [comment]
Hi,

I just gave a try on the TAMC script "gui_mimic_iso_peptide.py" from the most recent revision (#3362) in sassie-2.0. I did not see "resid<48" in line 106; instead, I did see it in line 36:

`
 36 post_basis_string_array = ['(segname UB2 and resid<48) or (segname UB2 and resid>48)']
`

However, changing "resid<48" to "resid < 48" here did not affect TAMC running. Maybe we were referring to some different driver script? If yes, could you attach the driver script you were using?

**Comment by stvn66** [comment]
This may be an issue caused by what is on SASSIE-web and in the svn differing from this repo.  I will look into this more and post back here.

**Comment by stvn66** [comment]
@hailiangzhang, try entering your input on [sassie-web](https://sassie-web.chem.utk.edu/sassie2/).  Here is the [log file](https://sassie-web.chem.utk.edu/sassie2/results/users/schowell/isopeptide_demo/monte_carlo_20160902-162323.sassie_log).  It breaks when parsing the flexible and post input.

**Comment by stvn66** [comment]
The problem is that the input parsing does not use the basis filtering.This is from `sassie_2.0/trunk/sassie/simulate/monte_carlo/monte_carlo_utilities/isopeptide_bond_torsion/isopeptide_bond_torsion_parameters.py` which is the code running on SASSIE-web:
```
def build_basis_strings(residue_main_pivots,residue_main_pivots_outside,residue_main_pivots_list, isopeptide_basis_string):

    '''
    method to create basis strings for each main pivot in each residue
    '''
    cter = isopeptide_basis_string.split('or')[0] ## @NOTE to ZHL: assume contract
    lys = isopeptide_basis_string.split('or')[1] ## @NOTE to ZHL: assume contract

    cter_list = cter.split()
    cter_resid = int(cter_list[cter_list.index('resid')+1])
    cter_segname = cter_list[cter_list.index('segname')+1]
    lys_list = lys.split()
    lys_resid = int(lys_list[lys_list.index('resid')+1])
    lys_segname = lys_list[lys_list.index('segname')+1]
```

It should instead be something like:

```
import sassie.util.basis_to_python as basis_to_python

cter_basis_string = isopeptide_basis_string + ' and resname LYS'
cter_basis = basis_to_python.parse_basis(cter_basis_string )
error, cter_mask = mol.get_subset_mask(cter_basis)
```

**Comment by hailiangzhang** [comment]
Yes, I should have use basis_to_python to parse the basis string; however, Isopeptide basis string follows a different contract compared to other regular moveset due to its unique topology.

Attached is the modified "isopeptide_bond_torsion_parameters.py" to fix this bug (not tested), and following are the changes (reported from git diff):

-    lys_list = lys.split()
-    lys_resid = int(lys_list[lys_list.index('resid')+1])
-    lys_segname = lys_list[lys_list.index('segname')+1]
+
+    basis_python = basis_to_python.parse_basis(cter)
+    r_resid = re.compile(r'resid\[i\]\s*==\s*("|\'{0,1})([\w\'"]+)\1')
+    lys_resid = int(r_resid.search(basis_python).groups()[1])
+    r_segname = re.compile(r'segname\[i\]\s*==\s*("|\'{0,1})([\w\'"]+)\1')
+    lys_segname  = r_segname.search(basis_python).groups()[1]

[isopeptide_bond_torsion_parameters.py.tar.gz](https://github.com/madscatt/zazzie/files/454112/isopeptide_bond_torsion_parameters.py.tar.gz)

**Comment by madscatt** [comment]
NOTE:  the DOCs need to state that the c-terminal part of the flexible region MUST come before the LYS part.

**Comment by stvn66** [comment]
The current implementation of the post region seems to provide an unnecessary vulnerability.  The current `gui_mimic` script has the post regions as follows:

 forward: `(segname UB2 and resid < 48) or (segname UB2 and resid > 48)`
reverse: `(segname UB1 and resid < 76) or (segname UB1 and resid > 76)`

Will it **always** be such that the two statements before and after the `or` are identical? If so, this should be consolidated to remove the `or` and the redundancy.  As is, it does not make sense: selection A **or** selection A?  Also, if they should be redundant we need to add error handling to catch the situation where a user mistypes one of the two repeated options.

**Comment by stvn66** [comment]
I am not sure what is gained by requiring that the c-terminal residue of the flexible region come before the lysine residue.  Having this requirement mean there has to be a test in the input filter to check that this is the case.  But if a test is already going to be run to determine that the correct residue was designated as the c-terminal/lysine, why not include that test as input parsing, thereby reducing the input constraints?  What is gained by throwing an error rather than switching the input?

**Comment by stvn66** [comment]
I am now able to enter input comparable to the other modules.
