### ISSUE TITLE
input filter boolean

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#53]
Need to remove t, f, true, false as valid variable inputs and just accept "True" or "False".  Take a final look at whether we will accept boolean types directly and not as strings.

**Comment by StevenCHowell** [comment]
I think it makes more sense to only accept boolean types directly, rather than abstract them into strings.  Why add the abstraction?

**Comment by madscatt** [comment]
Not an abstraction per se, but one should consider the system-wide definitions of input variables throughout sassie as strings.  The move of one variable type as different breaks that design decision so it is worth considering.  The initial move to pull booleans outside of this previous long-standing string only input rule was to allow developers to use boolean flags without worrying about type-conversion that is nice behavior especially to manage input decision trees in GUIs.  It isn't the end of the world if we continue to allow this distinction of boolean types and thus we won't change the 2.0 use of booleans directly and not as strings.  Modules moved from 1.0 to 2.0 will have to be changed as well as their associated tests.
